export const apps = [
  {
    id: 'jebi',
    name: 'jebi',
    tagline: 'The terminal that thinks with you.',
    description: 'A supercharged terminal for Mac with built-in AI that understands your session and slash commands for everything.',
    href: 'https://jebi.sh',
    logo: '/apps/jebi.png',
    accent: '#8be9fd',
    domain: 'jebi.sh',
    availability: 'github',
    availabilityLabel: 'Open source on GitHub',
    availabilityHref: 'https://github.com/jebi-sh/jebi',
    productHuntHref: 'https://www.producthunt.com/products/jebi-the-terminal-that-thinks-with-you',
  },
  {
    id: 'joy',
    name: 'Joy',
    tagline: 'Every win deserves confetti.',
    description: 'A menu bar app that watches GitHub stars, Stripe sales, and Docker Hub pulls, then celebrates when something great happens.',
    href: 'https://joy.jawahar.sh',
    logo: '/apps/joy.png',
    accent: '#bd93f9',
    domain: 'joy.jawahar.sh',
    availability: 'app-store',
    availabilityLabel: 'Available on the App Store',
  },
  {
    id: 'juno-chess',
    name: 'Juno',
    tagline: 'Coming soon.',
    description: '',
    href: '',
    logo: '/apps/juno-chess.png',
    accent: '#ffb86c',
    domain: 'Coming soon',
    availability: 'coming-soon',
    availabilityLabel: 'Coming soon',
  },
];
